### ISSUE TITLE
Sticky Hands

### ISSUE THREAD

**Issue by 25fan** [ncrecc/ncrmod#52] opened 2020-09-14 18:48 UTC
After Shocking Sticky Hands with the Sneezy? rule in place, I can't use my equipment, end turn, flee or Autoroll (full limit break). Sticky Hands had already used Pickpocket, but Run Away! was affected by the Sneezy? rule. 

When Run Away! is shocked the turn before Pickpocket is used instead, Sticky Hands doesn't end his turn after using Pickpocket.
![StickySituation](https://user-images.githubusercontent.com/71286868/93125329-e38d5480-f6c2-11ea-8a2b-391b843aa1f8.PNG)

This was encountered in the Robot NCR round.

**Comment by ncrecc** [comment] 2020-09-14 18:55
Re: the scenario shown on the image, what equipment did you have? Did the game softlock right after you ended your turn or after Sticky Hands ended his turn?

**Comment by ncrecc** [comment] 2020-09-14 18:55
Although maybe this is a vanilla bug, enemies handle slots very weirdly right now (even non-multislot items: https://discordapp.com/channels/423894813646127114/432114401177370624/755139446457762003 )

**Comment by 25fan** [comment] 2020-09-14 18:58
![image](https://user-images.githubusercontent.com/71286868/93126532-5e0aa400-f6c4-11ea-8855-0349a5bb826c.png)

The softlock was after Sticky Hands' turn ended.

**Comment by 25fan** [comment] 2020-09-14 19:03
Also, after Sticky Hands used Run Away!, the in-battle music didn't stop, but started playing at the same time as the music between battles. It stopped upon reaching a new floor, after rule selection.

**Comment by ncrecc** [comment] 2020-09-14 19:06
The music glitch is vanilla.
Figured out the cause of the softlock: AI, for some reason, gets very confused when a dice is assigned to a countdown is currently shocked. Fixed by having Sneezy? check that cards are unshocked before putting dice in them.

**Closed by ncrecc** 2020-09-14 19:06 UTC
